# Generated by Django 5.0.6 on 2024-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='pic_name',
        ),
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
